### ISSUE TITLE
11.0 payload

### ISSUE THREAD

**Issue by suzsuzuki** [ihaveamac/ninjhax2.x#3]
Hello. Could your please update your site for the 11.0 payload? (maybe 11.1 payload after released?) :)

**Comment by ihaveamac** [comment]
11.0 -> just use 10.6+ payloads
11.1 -> when it happens, probably.

**Comment by suzsuzuki** [comment]
Thank you sir!

**Comment by ghost** [comment]
Any plans to update the payloads for 11.1?

**Comment by suzsuzuki** [comment]
Any plans for 11.6? LOL...

**Comment by ihaveamac** [comment]
meh

**Comment by ihaveamac** [comment]
last comment before archiving the repository: I don't really feel like doing this because we have rosalina. if anyone else is interested in doing it, feel free to.
